INSERT INTO CURRENCY VALUES('GBP', true, 'British pound');

INSERT INTO CURRENCY_COUNTRIES VALUES('GBP', 'United Kingdom');
INSERT INTO CURRENCY_COUNTRIES VALUES('GBP', 'England');
INSERT INTO CURRENCY_COUNTRIES VALUES('GBP', 'Scotland');
INSERT INTO CURRENCY_COUNTRIES VALUES('GBP', 'Wales');
INSERT INTO CURRENCY_COUNTRIES VALUES('GBP', 'Northern Ireland');

INSERT INTO CURRENCY VALUES('EUR', true, 'Euro');

INSERT INTO CURRENCY_COUNTRIES VALUES('EUR', 'Germany');
INSERT INTO CURRENCY_COUNTRIES VALUES('EUR', 'Italy');
INSERT INTO CURRENCY_COUNTRIES VALUES('EUR', 'France');
INSERT INTO CURRENCY_COUNTRIES VALUES('EUR', 'Spain');
INSERT INTO CURRENCY_COUNTRIES VALUES('EUR', 'Portugal');
INSERT INTO CURRENCY_COUNTRIES VALUES('EUR', 'Greece');
INSERT INTO CURRENCY_COUNTRIES VALUES('EUR', 'Netherlands');
INSERT INTO CURRENCY_COUNTRIES VALUES('EUR', 'Austria');
INSERT INTO CURRENCY_COUNTRIES VALUES('EUR', 'Belgium');
INSERT INTO CURRENCY_COUNTRIES VALUES('EUR', 'Lithuania');
INSERT INTO CURRENCY_COUNTRIES VALUES('EUR', 'Ireland');

INSERT INTO CURRENCY VALUES('USD', true, 'United States dollar');
INSERT INTO CURRENCY_COUNTRIES VALUES('USD', 'United States');

INSERT INTO CURRENCY VALUES('BRL', false, 'Brazilian real');
INSERT INTO CURRENCY_COUNTRIES VALUES('BRL', 'Brazil');

INSERT INTO CURRENCY VALUES('CAD', false, 'Canadian dollar');
INSERT INTO CURRENCY_COUNTRIES VALUES('CAD', 'Canada');